name: shadertoy_wgpu
version: 2.0.3
description: >-
  shadertoy-wgpu description.
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.1 
  test: ^1.17.10
  dependency_validator: ^3.1.0