[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKING_DIRECTORY = "crates"
LIBRARY_FILE_EXT = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "unknown", mapping = { linux = "so", macos = "dylib", windows = "dll", openbsd = "so" } }
LIBRARY_SOURCE_NAME = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "libshadertoy_wgpu_ffi", mapping = { windows = "shadertoy_wgpu_ffi" } }
LIBRARY_TARGET_NAME = "shadertoy_wgpu_ffi"

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.dist]
script_runner = "@duckscript"
script = '''
cm_run_task release
cp target/release/${LIBRARY_SOURCE_NAME}.${LIBRARY_FILE_EXT} ../packages/shadertoy_wgpu/lib/src/ffi/blobs/${LIBRARY_TARGET_NAME}-${CARGO_MAKE_RUST_TARGET_ARCH}.${LIBRARY_FILE_EXT}
'''

[tasks.ci-release]
command = "cargo"
args = ["build", "--release", "--target", "${CARGO_MAKE_RUST_TARGET_TRIPLE}"]

[tasks.ci-dist]
script_runner = "@duckscript"
script = '''
cm_run_task ci-release
cp target/${CARGO_MAKE_RUST_TARGET_TRIPLE}/release/${LIBRARY_SOURCE_NAME}.${LIBRARY_FILE_EXT} target/blobs/${LIBRARY_TARGET_NAME}-${CARGO_MAKE_RUST_TARGET_ARCH}.${LIBRARY_FILE_EXT}
'''