name: shadertoy_alfred
version: 2.3.3
description: >-
  Shadertoy alfred support
publish_to: none
homepage: https://github.com/ivoleitao/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.8.0
  path: ^1.8.3
  # Other dependencies
  logger: ^1.3.0
  collection: ^1.17.1
  args: ^2.3.1
  pubspec_parse: ^1.2.2
  alfred_workflow: ^0.3.1
  shadertoy: ^2.3.0
  shadertoy_client: ^2.4.0
dev_dependencies:
  lints: ^2.0.1
  build_runner: ^2.3.3
  pubspec_builder: ^1.0.0
  dcli: ^2.0.1
  archive: ^3.3.6
  plist_parser: ^0.0.9

executables:
  st: shadertoy_alfred