name: shadertoy_alfred
version: 2.3.3
description: >-
  Shadertoy alfred support
publish_to: none
homepage: https://github.com/ivoleitao/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.10.0
  path: ^1.8.3
  # Other dependencies
  logger: ^2.0.2+1
  collection: ^1.18.0
  args: ^2.4.2
  pubspec_parse: ^1.2.3
  alfred_workflow: ^0.4.2
  shadertoy: ^2.3.0
  shadertoy_client: ^2.3.0
dev_dependencies:
  lints: ^2.1.1
  build_runner: ^2.4.6
  pubspec_builder: ^1.0.0
  dcli: ^3.1.0
  archive: ^3.4.4
  plist_parser: ^0.0.10

executables:
  st: shadertoy_alfred