name: shadertoy_cli
version: 2.0.3
publish_to: none
description: A sample command-line application.
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  path: ^1.8.2
  args: ^2.3.1
  progress_bar: ^1.0.0
  stash: ^4.0.1
  stash_sqlite: ^4.0.0
  drift: ^1.7.0
  # shadertoy: ^2.0.3
  shadertoy:
    path: ../shadertoy
  # shadertoy_client: ^2.0.3
  shadertoy_client:
    path: ../shadertoy_client
  # shadertoy_sqlite: ^2.0.3
  shadertoy_sqlite:
    path: ../shadertoy_sqlite
  shadertoy_wgpu:
    path: ../shadertoy_wgpu

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1

executables:
  shadertoy: shadertoy_cli
