name: shadertoy_cli
version: 2.0.3
publish_to: none
description: A sample command-line application.
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  path: ^1.8.1
  args: ^2.1.1
  progress_bar: ^1.0.0
  file: ^6.1.2
  moor: ^4.6.1+1
  # shadertoy: ^2.0.3
  shadertoy:
    path: ../shadertoy
  # shadertoy_client: ^2.0.3
  shadertoy_client:
    path: ../shadertoy_client
  # shadertoy_sqlite: ^2.0.3
  shadertoy_sqlite:
    path: ../shadertoy_sqlite
  shadertoy_wgpu:
    path: ../shadertoy_wgpu

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  dependency_validator: ^3.1.0

executables:
  shadertoy: shadertoy_cli
