name: shadertoy_cli
version: 1.0.0
publish_to: none
description: A sample command-line application.
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  enum_to_string: ^2.0.1
  args: ^2.1.1
  completion: ^1.0.0
  pool: ^1.5.0
  archive: ^3.1.2
  file: ^6.1.2
  moor: ^4.3.2
  glob: ^2.0.1
  # shadertoy_client: ^1.0.11
  shadertoy_client:
    path: ../shadertoy_client
  # shadertoy_sqlite: ^1.0.4
  shadertoy_sqlite:
    path: ../shadertoy_sqlite

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.8
