name: shadertoy_cli
version: 2.0.3
publish_to: none
description: A sample command-line application.
homepage: https://pub.dev/packages/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  path: ^1.8.1
  # Other dependencies  
  args: ^2.3.1
  progress_bar: ^1.0.0
  stash: ^4.3.3
  stash_sqlite: ^4.3.3
  drift: ^2.1.0
  shadertoy: ^2.0.3
  shadertoy_client: ^2.0.3
  shadertoy_sqlite: ^2.0.3
  shadertoy_wgpu:
    path: ../shadertoy_wgpu

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.5

executables:
  shadertoy: shadertoy_cli