name: shadertoy_cli
version: 2.1.1
publish_to: none
description: A sample command-line application.
homepage: https://github.com/ivoleitao/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  path: ^1.8.3
  # Other dependencies  
  args: ^2.4.2
  progress_bar: ^1.0.0
  stash: ^5.0.2
  stash_sqlite: ^5.0.2
  drift: ^2.13.0
  shadertoy: ^2.3.0
  shadertoy_client: ^2.3.0
  shadertoy_sqlite: ^2.1.4
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.8

executables:
  shadertoy: shadertoy_cli