name: shadertoy_sqlite
version: 2.1.4
description: >-
  A implementation of the shadertoy storage API using
  Sqlite as the storage backend
homepage: https://github.com/ivoleitao/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  path: ^1.8.3
  # Other dependencies
  resource_portable: ^3.1.0
  drift: ^2.13.0
  sqlite3: ^2.1.0
  shadertoy: ^2.3.0
dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.6
  test: ^1.24.8
  drift_dev: ^2.13.0
