name: shadertoy_sqlite
version: 1.0.5
publish_to: none
description: >-
  A implementation of the shadertoy storage API using
  Moor as the storage backend
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  enum_to_string: ^2.0.1
  moor: ^4.3.2
  shadertoy:
    path: ../shadertoy

dev_dependencies:
  pedantic: ^1.11.0
  build_runner: ^2.0.4
  test: ^1.17.5
  dio: ^4.0.0
  universal_platform: ^1.0.0+1
  dependency_validator: ^3.0.0
  moor_generator: ^4.3.1
