name: shadertoy_sqlite
version: 2.0.0-dev.1
publish_to: none
description: >-
  A implementation of the shadertoy storage API using
  Sqlite as the storage backend
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  enum_to_string: ^2.0.1
  moor: ^4.4.0
  shadertoy:
    path: ../shadertoy

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.0.5
  test: ^1.17.9
  dio: ^4.0.0
  universal_platform: ^1.0.0+1
  moor_generator: ^4.4.0
  dependency_validator: ^3.1.0
