name: shadertoy_sqlite
version: 2.0.0
description: >-
  A implementation of the shadertoy storage API using
  Sqlite as the storage backend
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  enum_to_string: ^2.0.1
  moor: ^4.4.1
  shadertoy: ^2.0.0
  # shadertoy:
  #  path: ../shadertoy

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.0.6
  test: ^1.17.10
  dio: ^4.0.0
  universal_platform: ^1.0.0+1
  moor_generator: ^4.4.1
  dependency_validator: ^3.1.0
