name: shadertoy_sqlite
version: 2.0.3
publish_to: none
description: >-
  A implementation of the shadertoy storage API using
  Sqlite as the storage backend
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  drift: ^1.2.0
  #shadertoy: ^2.0.1
  shadertoy:
    path: ../shadertoy

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.1.7
  test: ^1.20.1
  dio: ^4.0.4
  universal_platform: ^1.0.0+1
  drift_dev: ^1.2.0
