name: shadertoy_sqlite
version: 2.1.4
description: >-
  A implementation of the shadertoy storage API using
  Sqlite as the storage backend
homepage: https://github.com/ivoleitao/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  path: ^1.8.2
  # Other dependencies
  resource_portable: ^3.0.0
  drift: ^2.2.0
  sqlite3: ^1.9.1
  shadertoy: ^2.3.0
dev_dependencies:
  lints: ^2.0.1
  build_runner: ^2.3.2
  test: ^1.21.7
  drift_dev: ^2.2.0+1
