name: shadertoy_sqlite
version: 2.0.3
publish_to: none
description: >-
  A implementation of the shadertoy storage API using
  Sqlite as the storage backend
homepage: https://pub.dev/packages/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  drift: ^1.7.1
  #shadertoy: ^2.0.1
  shadertoy:
    path: ../shadertoy

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.2.0
  test: ^1.21.4
  dio: ^4.0.6
  universal_platform: ^1.0.0+1
  drift_dev: ^1.7.0
