name: shadertoy_sqlite
version: 2.1.1
description: >-
  A implementation of the shadertoy storage API using
  Sqlite as the storage backend
homepage: https://github.com/ivoleitao/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  path: ^1.8.1
  # Other dependencies
  resource_portable: ^3.0.0
  drift: ^2.1.0
  sqlite3: ^1.9.0
  shadertoy: ^2.1.1

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.2.0
  test: ^1.21.5
  drift_dev: ^2.1.0
