name: shadertoy_client
version: 2.0.3
publish_to: none
description: >-
  An http client implementation of the shadertoy API using
  Dio Http client. Supports the REST API (using an application key) 
  and the Site API (registered and anonymous users)
homepage: https://pub.dev/packages/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.7.0
  path: ^1.8.1
  # Other dependencies
  pool: ^1.5.1
  retry: ^3.1.0
  dio: ^4.0.6
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  html: ^0.15.0
  intl: ^0.17.0
  glob: ^2.1.0
  stash: ^4.3.2
  # shadertoy: ^2.0.3
  shadertoy:
    path: ../shadertoy

dev_dependencies:
  lints: ^2.0.0
  equatable: ^2.0.3
  test: ^1.21.4
  dotenv: ^4.0.1
  universal_platform: ^1.0.0+1
  stash_memory: ^4.0.3
  shadertoy_sqlite:
    path: ../shadertoy_sqlite