name: shadertoy_client
version: 2.4.0
description: >-
  An http client implementation of the shadertoy API using
  Dio Http client. Supports the REST API (using an application key) 
  and the Site API (registered and anonymous users)
homepage: https://github.com/ivoleitao/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.8.0
  path: ^1.8.3
  # Other dependencies
  pool: ^1.5.1
  retry: ^3.1.0
  dio: ^5.0.3
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.1.2
  html: ^0.15.2
  intl: ^0.18.0
  glob: ^2.1.1
  stash: ^4.5.2
  shadertoy: ^2.3.0
dev_dependencies:
  lints: ^2.0.1
  equatable: ^2.0.5
  test: ^1.23.1
  dotenv: ^4.1.0
  universal_platform: ^1.0.0+1
  stash_memory: ^4.5.2
  shadertoy_sqlite: ^2.1.4