name: shadertoy_client
version: 1.0.12
publish_to: none
description: >-
  An http client implementation of the shadertoy API using
  Dio Http client. Supports the REST API (using an application key) 
  and the Site API (registered and anonymous users)
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  meta: ^1.4.0
  enum_to_string: ^2.0.1
  path: ^1.8.0
  file: ^6.1.2
  pool: ^1.5.0
  retry: ^3.1.0
  dio: ^4.0.0
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  html: ^0.15.0
  intl: ^0.17.0
  glob: ^2.0.1
  envify: ^2.0.0
  shadertoy:
    path: ../shadertoy

dev_dependencies:
  pedantic: ^1.11.0
  build_runner: ^2.0.4
  envify_generator: ^2.0.0
  test: ^1.17.5
  universal_platform: ^1.0.0+1
  dependency_validator: ^3.0.0