name: shadertoy_client
version: 2.0.3
publish_to: none
description: >-
  An http client implementation of the shadertoy API using
  Dio Http client. Supports the REST API (using an application key) 
  and the Site API (registered and anonymous users)
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  path: ^1.8.1
  pool: ^1.5.0
  stash: ^4.0.1
  retry: ^3.1.0
  dio: ^4.0.4
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  html: ^0.15.0
  intl: ^0.17.0
  glob: ^2.0.2
  # shadertoy: ^2.0.3
  shadertoy:
    path: ../shadertoy

dev_dependencies:
  lints: ^1.0.1
  equatable: ^2.0.3
  test: ^1.20.1
  dotenv: ^3.0.0
  universal_platform: ^1.0.0+1
  stash_memory: ^4.0.1
  shadertoy_sqlite:
    path: ../shadertoy_sqlite