name: shadertoy
version: 2.0.2
description: >-
  Main entities and contracts supported by the shadertoy REST and WEB APIs. 
  Can be used to create shadertoy web or persistent clients.
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.1.0

dev_dependencies:
  lints: ^1.0.1 
  build_runner: ^2.0.6
  json_serializable: ^5.0.0
  test: ^1.17.10
  dependency_validator: ^3.1.0