name: shadertoy
version: 2.0.3
publish_to: none
description: >-
  Main entities and contracts supported by the shadertoy REST and WEB APIs. 
  Can be used to create shadertoy web or persistent clients.
homepage: https://pub.dev/packages/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  path: ^1.8.1
  # Other dependencies
  equatable: ^2.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  test: ^1.21.4