name: shadertoy
version: 2.0.0-dev.1
description: >-
  Main entities and contracts supported by the shadertoy REST and WEB APIs. 
  Can be used to create shadertoy web or persistent clients.
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.2
  json_annotation: ^4.0.1

dev_dependencies:
  pedantic: ^1.11.0
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  test: ^1.17.5
  dependency_validator: ^3.0.0