name: shadertoy
version: 2.0.3
publish_to: none
description: >-
  Main entities and contracts supported by the shadertoy REST and WEB APIs. 
  Can be used to create shadertoy web or persistent clients.
homepage: https://github.com/ivoleitao/shadertoy

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  path: ^1.8.2
  json_annotation: ^4.5.0

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  test: ^1.21.1