name: shadertoy
version: 2.1.2
description: >-
  Main entities and contracts supported by the shadertoy REST and WEB APIs. 
  Can be used to create shadertoy web or persistent clients.
homepage: https://github.com/ivoleitao/shadertoy
repository: https://github.com/ivoleitao/shadertoy
issue_tracker: https://github.com/ivoleitao/shadertoy/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  path: ^1.8.2
  # Other dependencies
  equatable: ^2.0.5
  json_annotation: ^4.7.0

dev_dependencies:
  lints: ^2.0.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  test: ^1.21.7