name: CI

on:
  schedule:
    - cron: '*/30 8 * * *'
  push:
    branches:
      - develop
    paths:
      - 'Makefile.toml'      
      - 'melos.yaml'
      - 'crates/**'
      - 'packages/**'
      - '.github/workflows/ci.yml'

  pull_request:
    branches:
      - develop
    paths:
      - 'Makefile.toml'      
      - 'melos.yaml'
      - 'crates/**'
      - 'packages/**'
      - '.github/workflows/ci.yml'

jobs:
  rust:
    name: Rust

    strategy:
      matrix:
        host: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        include:
          - host: ubuntu-latest
            toolchain: stable
          - host: macos-latest
            toolchain: stable
          - host: windows-latest
            toolchain: stable

    runs-on: ${{ matrix.host }}

    steps:
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Install tools
        uses: davidB/rust-cargo-make@v1
        with:
          version: 'latest'

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: make
          args: ci-dist

      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: crates/target/dist
  dart:
    name: Dart
    needs: rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']

    steps:
      - name: Setup os
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev -y

      - name: Set up dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install tools
        run: |
          pub global activate melos

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Download shared libraries 
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: packages/shadertoy_wgpu/lib/src/ffi/blobs

      - name: Bootstrap
        run: |
          melos bootstrap
          
      - name: Build
        run: |
          melos run build
          
      - name: Linter
        run: |
          melos run dependency-validator
          melos run format
          melos run analyze

      - name: Test
        run: |
          melos run test

      - name: Documentation
        run: |
          melos run doc

      - name: Verify
        run: |
          melos run verify

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          branch: develop
          default_author: github_actions