name: Dart Coverage

on:
  push:
    branches:
      - master
    paths:
      - 'packages/**'
      - '.github/workflows/dart_coverage.yml'

jobs:
  coverage:
    name: Coverage

    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup os
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev -y

      - name: Set up dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          pub global activate melos
          
      - name: Bootstrap
        run: |
          melos bootstrap

      - name: Coverage
        run: |
          melos run coverage

      - name: Upload coverage
        run: |
          melos run codecov