name: Coverage

on:
  push:
    branches:
      - master
    paths:
      - 'packages/**'
      - '.github/workflows/dart-coverage.yml'

jobs:
  coverage:
    name: Dart coverage

    strategy:
      matrix:
        host: ['ubuntu-latest']
        sdk: ['stable']

    runs-on: ${{ matrix.host }}

    steps:
      - name: Install libraries
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev -y

      - name: Set up dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          dart pub global activate melos
          
      - name: Bootstrap
        run: |
          melos bootstrap

      - name: Coverage
        run: |
          melos run coverage
          melos run codecov