name: Dart CI

on:
  schedule:
    - cron: '*/30 8 * * *'
  push:
    branches:
      - develop
    paths:
      - 'melos.yaml'
      - 'packages/**'
      - '.github/workflows/dart_ci.yml'

  pull_request:
    branches:
      - develop
    paths:
      - 'melos.yaml'
      - 'packages/**'
      - '.github/workflows/dart_ci.yml'

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']

    steps:
      - name: Setup os
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev -y

      - name: Set up dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          pub global activate melos
          pub global activate pana

      - name: Bootstrap
        run: |
          melos bootstrap
          
      - name: Build
        run: |
          melos run build
          
      - name: Linter
        run: |
          melos run dependency-validator
          melos run format
          melos run analyze

      - name: Test
        run: |
          melos run test

      - name: Documentation
        run: |
          melos run doc

      - name: Calculate scores
        run: |
          melos run pana