name: Github Release
on:
  push:
    tags:
      - 'shadertoy_alfred-v*'

jobs:
  alfred_workflow:
    name: Github release Alfred workflow

    strategy:
      matrix:
        os: ['ubuntu-latest']
        channel: ['stable']        
        flutter_version: ['3.13.6']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
          flutter-version: ${{ matrix.flutter_version }}
      
      - name: Install packages
        run: |
          dart pub global activate melos
          dart pub global activate dcli

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Bootstrap
        run: |
          melos bs

      - name: Build
        run: |
          melos build

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          body_path: packages/shadertoy_alfred/CHANGELOG.md
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            packages/shadertoy_alfred/target/*/*.alfredworkflow