name: Github Release
on:
  push:
    tags:
      - 'shadertoy_alfred-v*'

jobs:
  alfred_workflow:
    name: Github release Alfred workflow

    strategy:
      matrix:
        host: ['macos-latest']
        sdk: ['stable']

    runs-on: ${{ matrix.host }}

    steps:
      - name: Set up dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      
      - name: Install packages
        run: |
          dart pub global activate melos
          dart pub global activate dcli

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Bootstrap
        run: |
          melos bs

      - name: Build
        run: |
          melos build

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          body_path: packages/shadertoy_alfred/CHANGELOG.md
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            packages/shadertoy_alfred/target/*/*.alfredworkflow