name: Plantuml
on:
  push:
    paths:
      - "**.pu"
    branches:
      - develop
jobs:
  plantuml:
    runs-on: ubuntu-latest
    env:
      UML_FILES: ".pu"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep ${{ env.UML_FILES }} | xargs)"
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -v -tsvg ${{ steps.getfile.outputs.files }}
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.15.3
        with:
          commit_message: "Generate SVG and PNG images for PlantUML diagrams"
          branch: ${{ github.head_ref }}
