name: Rust CI

on:
  schedule:
    - cron: '*/30 8 * * *'
  push:
    branches:
      - develop
    paths:
      - 'Makefile.toml'      
      - 'crates/**'
      - '.github/workflows/rust-ci.yml'

  pull_request:
    branches:
      - develop
    paths:
      - 'Makefile.toml'      
      - 'crates/**'
      - '.github/workflows/rust-ci.yml'

jobs:
  rust:
    name: Rust CI

    strategy:
      matrix:
        host: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        toolchain: ['stable']

    runs-on: ${{ matrix.host }}

    steps:
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Install tools
        uses: davidB/rust-cargo-make@v1
        with:
          version: 'latest'

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: make
          args: ci-dist