name: Rust CI

on:
  schedule:
    - cron: '*/30 8 * * *'
  push:
    branches:
      - develop
    paths:
      - 'crates/**'
      - '.github/workflows/rust_ci.yml'

  pull_request:
    branches:
      - develop
    paths:
      - 'crates/**'
      - '.github/workflows/rust_ci.yml'

jobs:
  ci:
    name: CI

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        crate: ['shadertoy_wgpu_ffi']
        include:
          - os: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            toolchain: stable
            target: x86_64-pc-windows-msvc            
          - os: macos-latest
            toolchain: stable
            target: x86_64-apple-darwin            


    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.arch }}
          override: true

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build
        uses: marcopolo/cargo@master
        with:
          use-cross: true
          command: build
          working-directory: crates/${{ matrix.crate }}
          args: --release --target ${{ matrix.target }}