name: Rust CI

on:
  push:
    branches:
      - master
    paths:
      - 'Makefile.toml'      
      - 'crates/**'
      - '.github/workflows/rust-release.yml'

jobs:
  build:
    name: Rust Build

    strategy:
      matrix:
        host: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        toolchain: ['stable']

    runs-on: ${{ matrix.host }}

    steps:
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Install tools
        uses: davidB/rust-cargo-make@v1
        with:
          version: 'latest'

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: make
          args: dist

      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: crates/target/dist
  release:
    name: Rust Dist

    needs: build

    strategy:
      matrix:
        host: ['ubuntu-latest']
        sdk: ['stable']

    runs-on: ${{ matrix.host }}

    steps:
      - name: Download shared libraries 
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist