name: Rust CI

on:
  schedule:
    - cron: '*/30 8 * * *'
  push:
    branches:
      - develop
    paths:
      - 'crates/**'
      - '.github/workflows/rust_ci.yml'

  pull_request:
    branches:
      - develop
    paths:
      - 'crates/**'
      - '.github/workflows/rust_ci.yml'

jobs:
  ci:
    name: CI

    strategy:
      matrix:
        host: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        crate: ['shadertoy_wgpu']
        package: ['shadertoy_wgpu']
        library: ['shadertoy_wgpu']
        include:
          - host: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-gnu
            os: linux
            bitness: 64
            extension: so
          - host: macos-latest
            toolchain: stable
            target: x86_64-apple-darwin            
            os: mac
            bitness: 64
            extension: dylib
          - host: windows-latest
            toolchain: stable
            target: x86_64-pc-windows-msvc            
            os: win
            bitness: 64
            extension: dll

    runs-on: ${{ matrix.host }}

    steps:
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.arch }}
          override: true

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build ${{ matrix.crate }}
        uses: marcopolo/cargo@master
        with:
          use-cross: true
          command: build
          working-directory: crates/${{ matrix.crate }}
          args: --release --target ${{ matrix.target }}

      - name: Copy crates/${{ matrix.crate }}/target/${{ matrix.target }}/release/lib${{ matrix.crate }}.${{ matrix.extension }} to packages/${{ matrix.package }}/lib/src/ffi/blobs/${{ matrix.library }}-${{ matrix.os }}${{ matrix.bitness }}.${{ matrix.extension }}
        run: | 
          mkdir packages/${{ matrix.package }}/lib/src/ffi/blobs 
          cp crates/${{ matrix.crate }}/target/${{ matrix.target }}/release/lib${{ matrix.crate }}.${{ matrix.extension }} packages/${{ matrix.package }}/lib/src/ffi/blobs/${{ matrix.library }}-${{ matrix.os }}${{ matrix.bitness }}.${{ matrix.extension }}
        shell: bash

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions